apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-api
  labels:
    app: assets
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assets
      component: api
  template:
    metadata:
      labels:
        app: assets
        component: api
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: api
          image: ghcr.io/alsairy/assets_platform/api:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: assets-config }
            - secretRef:    { name: assets-secrets }
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            httpGet: { path: /health, port: 8080 }
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - { name: tmp,            mountPath: /tmp }
      volumes:
        - { name: tmp,            emptyDir: {} }
