apiVersion: v1
kind: Service
metadata:
  name: assets-api
  labels:
    app: assets
    component: api
spec:
  type: ClusterIP
  selector:
    app: assets
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
