version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  flowable:
    image: flowable/flowable-rest:6.8.0
    container_name: assets-flowable
    environment:
      FLOWABLE_DATABASE_TYPE: postgres
      FLOWABLE_DATABASE_HOST: db
      FLOWABLE_DATABASE_PORT: 5432
      FLOWABLE_DATABASE_NAME: appdb
      FLOWABLE_DATABASE_USERNAME: app
      FLOWABLE_DATABASE_PASSWORD: app
      FLOWABLE_DATABASE_SCHEMA_UPDATE: true
      FLOWABLE_REST_APP_ADMIN_USER: admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/flowable-rest/service/management/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on: [db]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on: [db]

  api:
     build: { context: ./backend, dockerfile: Dockerfile }
     environment:
       ASPNETCORE_URLS: http://+:8080
       ASPNETCORE_ENVIRONMENT: Development
       ConnectionStrings__Default: Host=db;Port=5432;Database=appdb;Username=app;Password=app
       OIDC__AUTHORITY: http://keycloak:8080/realms/moe
       FLOWABLE__BASEURL: http://flowable:8080/flowable-rest
       FLOWABLE__USERNAME: admin
       FLOWABLE__PASSWORD: test
       OCR__PROVIDER: Fake
     depends_on:
       db:
         condition: service_started
       flowable:
         condition: service_healthy
       keycloak:
         condition: service_healthy
     ports: ["8080:8080"]

  web:
    build: { context: ./frontend/web, dockerfile: Dockerfile }
    ports: ["5173:80"]
    depends_on: [api]

volumes: { pgdata: {} }
