apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-api
  labels:
    app: assets-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assets-api
  template:
    metadata:
      labels:
        app: assets-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: api
          image: ghcr.io/alsairy/assets_platform/api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: assets-config
            - secretRef:
                name: assets-secrets
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
