apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assets-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: assets.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assets-api
                port:
                  number: 80
