apiVersion: v1
kind: Secret
metadata:
  name: assets-secrets
type: Opaque
stringData:
  CONNECTION_STRING: "Host=postgres;Port=5432;Database=appdb;Username=app;Password=app"
  FLOWABLE_USERNAME: "rest-admin"
  FLOWABLE_PASSWORD: "test"
