apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-worker
  labels:
    app: assets
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
      component: worker
  template:
    metadata:
      labels:
        app: assets
        component: worker
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: worker
          image: ghcr.io/alsairy/assets_platform/worker:{{VERSION}}
          imagePullPolicy: IfNotPresent
          args: ["--run-worker=OcrJobWorker"]
          envFrom:
            - configMapRef:
                name: assets-config
            - secretRef:
                name: assets-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["sh","-c","echo ok"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: tmp
          emptyDir: {}
