apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: assets-dev
resources:
  - ../../base
  - hpa-api.yaml
  - hpa-worker.yaml
  - pdb-api.yaml
  - pdb-worker.yaml
  - netpol-default-deny-egress.yaml
  - netpol-allow-ingress-to-api.yaml
  - netpol-allow-api-egress.yaml
  - netpol-allow-worker-egress.yaml
patches:
  - path: patch-deploy-api-replicas.yaml
  - path: patch-deploy-worker-replicas.yaml
  - path: patch-ingress.yaml
images:
  - name: ghcr.io/alsairy/assets_platform/api
    newTag: "{{VERSION}}"
  - name: ghcr.io/alsairy/assets_platform/worker
    newTag: "{{VERSION}}"
configMapGenerator:
  - name: assets-config
    behavior: merge
    literals:
      - OIDC__AUTHORITY=https://idp.dev.example.com/realms/moe
      - OIDC__AUDIENCE=assets-api
      - Flowable__BaseUrl=https://flowable.dev.example.com/flowable-rest
      - GoogleCloud__ProjectId=dev-gcp-project
      - GCS__BucketName=dev-gcs-bucket
