apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-egress
spec:
  podSelector:
    matchLabels:
      app: assets
      component: worker
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
